# Generated by Django 3.0.2 on 2020-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('in_th', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mm_th', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nom', models.CharField(max_length=50)),
                ('dia_in', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longueur_sortie_outil', models.DecimalField(decimal_places=2, max_digits=5)),
                ('action', models.CharField(max_length=50)),
            ],
        ),
    ]
