# Generated by Django 3.0.2 on 2020-02-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('fabricant', models.CharField(max_length=50)),
                ('type_machine', models.CharField(max_length=50)),
                ('modèle', models.CharField(max_length=50)),
                ('num_série', models.BigIntegerField()),
            ],
        ),
    ]
