# Generated by Django 3.0.2 on 2020-02-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_modele'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_essais', models.IntegerField()),
                ('état', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vitesse', models.IntegerField()),
                ('vitesse_coupe', models.IntegerField()),
                ('rpm', models.IntegerField()),
                ('avancée', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alimentation_coupe', models.CharField(max_length=50)),
                ('temps_coupe', models.DurationField()),
                ('nom_matière', models.CharField(max_length=50)),
                ('type_machine', models.CharField(max_length=50)),
                ('nom_machine', models.CharField(max_length=50)),
                ('fabricant', models.CharField(max_length=50)),
                ('modèle', models.CharField(max_length=50)),
                ('nom_outil', models.CharField(max_length=50)),
            ],
        ),
    ]
